name: Deployment

on:
  push:
    branches: [ main ]

jobs:
   deploy:
     runs-on: self-hosted
     steps:
       - name: Pull na Docker image
         run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kotlin-cicd-atividade:latest

       - name: Remove no Container
         run: docker rm -f kotlin-cicd || true

       - name: Rodando container
         run: docker run --name kotlin-cicd -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/kotlin-cicd-atividade:latest