name: Validate

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, reopened ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clonar repositório"
        uses: actions/checkout@v4

      - name: Baixar a JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Buildar com Maven
        run: |
          cd calcular-inss
          mvn -B package -DskipTests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Clonar repositório"
        uses: actions/checkout@v4

      - name: Baixar a JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Executar testes
        run: |
          cd calcular-inss
          mvn test
  docker:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: "Clonar repositório"
        uses: actions/checkout@v4

      - name: Configurando QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurando Docker
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Buildar e publicar
        uses: docker/build-push-action@v3
        with:
          context: ./calcular-inss
          file: ./calcular-inss/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kotlin-cicd:latest

    name: Deployment
    on:
      push:
        branches: [ main ]

    jobs:
      deploy:
        runs-on: self-hosted
        steps:
          - name: Pull na Docker image
            run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kotlin-cicd:latest

          - name: Remove no Container
            run: docker rm -f kotlin-cicd || true

          - name: Rodando container
            run: docker run --name kotlin-cicd -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/kotlin-cicd:latest